name: Build and Deploy Jupyter Book

# Controls when the action will run.
on:
  push:
    branches:
      - main  # Or master, or whatever your default branch is
    paths:  # Only run if these files/folders change
      - '**.md'
      - '**.ipynb'
      - '_toc.yml'
      - '_config.yml'
      - 'requirements.txt' # Rebuild if dependencies change
      # Add any other source file patterns relevant to your book
      # e.g., 'images/**', 'custom_css/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4 # Or v3

      - name: Set up Python
        uses: actions/setup-python@v5 # Or v4
        with:
          python-version: '3.10' # Choose a Python version compatible with your book

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install jupyter-book ghp-import # Ensure these are installed

      - name: Build the Jupyter Book
        run: |
          # Assuming your book is in the root. If it's in a subdirectory like 'docs/',
          # then use: jupyter-book build docs/
          jupyter-book build .

      - name: Deploy to GitHub Pages
        # This uses the popular peaceiris/actions-gh-pages action
        # It will push the contents of _build/html to the gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          # Optional: if you have a custom domain
          # cname: your.custom.domain.com
          # Optional: to create a .nojekyll file (important for non-Jekyll sites)
          # The action usually handles this well, but can be explicit:
          # keep_files: false # This might be default or true depending on action version
          # force_orphan: true # Creates a fresh gh-pages branch history
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
